"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Download,Link2,Pencil,Plus,Search,Trash2} from "lucide-react";
import {Button} from "@/components/ui/button"; import {Input} from "@/components/ui/input"; import {Badge} from "@/components/ui/badge";
import {Card,CardContent} from "@/components/ui/card";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from "@/components/ui/alert-dialog";
const STATUSES=["Applied","Assessment","Interview","Offer","Rejected","Withdrawn"] as const; type Status=typeof STATUSES[number];
type App={id:number;company:string;position:string;appliedDate:string;status:Status;jobUrl:string;notes:string;updatedAt:string};
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const fresh=()=>({company:"",position:"",appliedDate:localDate(),status:"Applied" as Status,jobUrl:"",notes:""});
const colors:Record<Status,string>={Applied:"bg-sky-50 text-sky-700 border-sky-200",Assessment:"bg-violet-50 text-violet-700 border-violet-200",Interview:"bg-amber-50 text-amber-800 border-amber-200",Offer:"bg-emerald-50 text-emerald-700 border-emerald-200",Rejected:"bg-rose-50 text-rose-700 border-rose-200",Withdrawn:"bg-slate-100 text-slate-600 border-slate-200"};
export default function Home(){
 const [items,setItems]=useState<App[]>([]),[form,setForm]=useState(fresh),[editing,setEditing]=useState<number|null>(null),[deleting,setDeleting]=useState<number|null>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("All"),[loading,setLoading]=useState(true),[reading,setReading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function load(){try{const r=await fetch("/api/applications",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.applications);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load applications")}finally{setLoading(false)}}
 useEffect(()=>{let active=true;fetch("/api/applications",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(active)setItems(d.applications)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load applications")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const visible=useMemo(()=>items.filter(x=>(filter==="All"||x.status===filter)&&(!query.trim()||`${x.company} ${x.position}`.toLowerCase().includes(query.trim().toLowerCase()))),[items,filter,query]);
 const counts={total:items.length,active:items.filter(x=>!["Rejected","Withdrawn"].includes(x.status)).length,interviews:items.filter(x=>x.status==="Interview").length,offers:items.filter(x=>x.status==="Offer").length};
 async function save(e:FormEvent){e.preventDefault();if(saving)return;setSaving(true);setError("");try{const r=await fetch(editing?`/api/applications/${editing}`:"/api/applications",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save application");setEditing(null);setForm(fresh());await load()}catch(e){setError(e instanceof Error?e.message:"Could not save application")}finally{setSaving(false)}}
 function edit(x:App){setEditing(x.id);setForm({company:x.company,position:x.position,appliedDate:x.appliedDate,status:x.status,jobUrl:x.jobUrl,notes:x.notes});window.scrollTo({top:0,behavior:"smooth"})}
 async function status(x:App,s:Status){try{const r=await fetch(`/api/applications/${x.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...x,status:s})});if(!r.ok)throw new Error("Could not update status");await load()}catch(e){setError(e instanceof Error?e.message:"Could not update status")}}
 async function remove(){if(!deleting)return;try{const r=await fetch(`/api/applications/${deleting}`,{method:"DELETE"});if(!r.ok)throw new Error("Could not delete application");if(editing===deleting){setEditing(null);setForm(fresh())}setDeleting(null);await load()}catch(e){setError(e instanceof Error?e.message:"Could not delete application")}}
 async function fill(){if(!form.jobUrl)return;setReading(true);setError("");try{const r=await fetch("/api/job-preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:form.jobUrl})}),d=await r.json();if(!r.ok)throw new Error(d.error);setForm(f=>({...f,company:d.company||f.company,position:d.position||f.position,jobUrl:d.url||f.jobUrl}))}catch(e){setError(e instanceof Error?e.message:"Could not read this job link.")}finally{setReading(false)}}
 function csv(){const q=(v:string|number)=>`"${String(v).replaceAll('"','""')}"`,rows=[["Company","Position","Date Applied","Status","Job Link","Notes","Last Updated"],...items.map(x=>[x.company,x.position,x.appliedDate,x.status,x.jobUrl,x.notes,x.updatedAt])],url=URL.createObjectURL(new Blob([rows.map(r=>r.map(q).join(",")).join("\n")],{type:"text/csv"})),a=document.createElement("a");a.href=url;a.download=`job-applications-${localDate()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <main className="min-h-screen bg-[#f3f6f8] text-[#17212b]"><div className="mx-auto max-w-[1440px] px-4 py-6 sm:px-8 lg:px-12">
  <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-semibold uppercase tracking-[.18em] text-[#24775f]">Application workspace</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Job Search Tracker</h1></div><Button variant="outline" onClick={csv} disabled={!items.length} className="h-11 bg-white"><Download className="mr-2 size-4"/>Export CSV</Button></header>
  <section className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4" aria-label="Application summary">{[["Total applications",counts.total],["Active",counts.active],["Interviews",counts.interviews],["Offers",counts.offers]].map(([l,v])=><Card key={l} className="border-0 shadow-sm"><CardContent className="p-4 sm:p-5"><p className="text-sm text-slate-500">{l}</p><p className="mt-1 text-3xl font-bold">{v}</p></CardContent></Card>)}</section>
  <section className="mb-6 rounded-2xl border bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex flex-col gap-2 sm:flex-row"><Input type="url" placeholder="Paste a job posting link to fill the form" aria-label="Job posting link" value={form.jobUrl} onChange={e=>setForm({...form,jobUrl:e.target.value})} className="h-11 flex-1"/><Button type="button" variant="outline" onClick={fill} disabled={!form.jobUrl||reading} className="h-11"><Link2 className="mr-2 size-4"/>{reading?"Reading job...":"Fill from link"}</Button></div><form onSubmit={save} className="grid gap-3 lg:grid-cols-[1.1fr_1.4fr_.8fr_.9fr_auto]">
   <Input placeholder="Company name" aria-label="Company name" value={form.company} onChange={e=>setForm({...form,company:e.target.value})} required className="h-11"/><Input placeholder="Position" aria-label="Position" value={form.position} onChange={e=>setForm({...form,position:e.target.value})} required className="h-11"/><Input type="date" aria-label="Date applied" value={form.appliedDate} onChange={e=>setForm({...form,appliedDate:e.target.value})} required className="h-11"/><StatusSelect value={form.status} change={s=>setForm({...form,status:s})}/><Button disabled={saving||reading} className="h-11 bg-[#1f6f58] hover:bg-[#185b49]"><Plus className="mr-2 size-4"/>{editing?"Save changes":"Add application"}</Button>
   <Input placeholder="Notes (optional)" aria-label="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="h-11 lg:col-span-4"/>{editing&&<Button type="button" variant="ghost" onClick={()=>{setEditing(null);setForm(fresh())}}>Cancel edit</Button>}
  </form>{error&&<p role="alert" className="mt-3 text-sm font-medium text-rose-700">{error}</p>}</section>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:justify-between"><div className="relative w-full sm:max-w-sm"><Search className="absolute left-3 top-3 size-4 text-slate-400"/><Input placeholder="Search company or position" value={query} onChange={e=>setQuery(e.target.value)} className="h-10 pl-9"/></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="h-10 w-full sm:w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="All">All statuses</SelectItem>{STATUSES.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>
   {loading?<p className="p-10 text-center text-slate-500">Loading applications...</p>:visible.length===0?<div className="p-12 text-center"><p className="text-lg font-semibold">No applications found</p><p className="mt-1 text-sm text-slate-500">Add your first application above or change the filters.</p></div>:<Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Company</TableHead><TableHead>Position</TableHead><TableHead>Date applied</TableHead><TableHead>Status</TableHead><TableHead>Notes</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{visible.map(x=><TableRow key={x.id}><TableCell className="font-semibold">{x.jobUrl?<a href={x.jobUrl} target="_blank" rel="noreferrer" className="text-[#1f6f58] hover:underline">{x.company}</a>:x.company}</TableCell><TableCell>{x.position}</TableCell><TableCell>{new Date(`${x.appliedDate}T00:00:00`).toLocaleDateString()}</TableCell><TableCell><StatusSelect value={x.status} change={s=>status(x,s)} badge/></TableCell><TableCell className="max-w-[260px] truncate text-slate-500">{x.notes||"None"}</TableCell><TableCell><div className="flex justify-end"><Button size="icon" variant="ghost" onClick={()=>edit(x)} aria-label={`Edit ${x.company}`}><Pencil className="size-4"/></Button><Button size="icon" variant="ghost" onClick={()=>setDeleting(x.id)} aria-label={`Delete ${x.company}`} className="text-rose-700"><Trash2 className="size-4"/></Button></div></TableCell></TableRow>)}</TableBody></Table>}
  </section></div>
  <AlertDialog open={deleting!==null} onOpenChange={o=>!o&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this application?</AlertDialogTitle><AlertDialogDescription>This removes the record permanently. Export a CSV first if you may need it later.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep it</AlertDialogCancel><AlertDialogAction onClick={remove} className="bg-rose-700">Delete application</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
function StatusSelect({value,change,badge=false}:{value:Status;change:(s:Status)=>void;badge?:boolean}){return <Select value={value} onValueChange={v=>change(v as Status)}><SelectTrigger aria-label="Application status" className={badge?"h-8 border-0 p-0 shadow-none":"h-11 w-full"}><SelectValue>{badge?<Badge variant="outline" className={colors[value]}>{value}</Badge>:value}</SelectValue></SelectTrigger><SelectContent>{STATUSES.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>}
